# Generated by Django 6.0.5 on 2026-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
