# Generated by Django 6.0.5 on 2026-05-12 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('hospitality', 'Hospitality'), ('retail', 'Retail'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('admin', 'Admin & Office'), ('finance', 'Finance'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('hours_per_week', models.IntegerField()),
                ('job_type', models.CharField(default='part-time', max_length=50)),
                ('visa_sponsored', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
