# Generated by Django 6.0.5 on 2026-05-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('hospitality', 'Hospitality'), ('retail', 'Retail'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('admin', 'Admin & Office'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='hours_per_week',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('part-time', 'Part-time'), ('casual', 'Casual'), ('internship', 'Internship'), ('full-time', 'Full-time')], default='part-time', max_length=50),
        ),
    ]
